/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab;


import org.junit.Test;


import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//    System.out.println("hey its being run !!!");
//    }


    @Test public void testRoll_basicTest() {
        Library classUnderTest = new Library();
        int inputRolls = 9;
        assertEquals("Should return an array of the appropriate length",
        inputRolls, classUnderTest.Roll(inputRolls).length);
    }


    @Test public void testDuplicates(){
        Library classUnderTest = new Library();
        int[] inputArray = new int[]{1, 2, 2, 4};
        assertTrue("Should return true if duplicates in array",
        classUnderTest.Doop(inputArray));
    }


    @Test public void testAvgMker() {
        Library classUnderTest = new Library();
        int[] rolls = {4,2,7,4,10};
        double avg = classUnderTest.avgMaker(rolls);
        assertTrue("Returned average incorrect.", avg == (4+2+7+4+10)/5);
    }




}
